name: deepcloud-pidlrad
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - h5py
  - networkx
  - pip:
      - wandb
      - python-dotenv
      - einops
      - torchmetrics
      - torchinfo
      - requests
      - pyyaml
      - pillow
      - GitPython
      - sentry-sdk
      - setproctitle
